graphhopper:
  datareader.file: scotland-latest.osm.pbf
  gtfs.file: itm_scotland_gtfs.zip
  graph.location: graphs/great-britain-with-transit

  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost
